### ISSUE TITLE
missing Hardware tag for ODROIDC2

### ISSUE THREAD

**Issue by meveric** [hardkernel/linux#199] opened 2016-05-26 05:41 UTC
With the latest changes the board does no longer report the "Hardware" tag with ODROIDC2 in fact it's gone completely if you check under /proc/cpuinfo.
This actually causes a tons of checks to fail for me.
Please re-add "Hardware:  ODROID-C2" to the cpuinfo.

**Comment by Fourdee** [comment] 2016-05-26 10:53
> Please re-add "Hardware: ODROID-C2" to the cpuinfo.

DietPi scrapes this as a hardware identifier for the C2: https://github.com/Fourdee/DietPi/blob/master/dietpi/dietpi-obtain_hw_model#L95-L100. So would be nice to get this back.

**Comment by OtherCrashOverride** [comment] 2016-05-26 18:31
This issue was not present in the manual merge I did.  The HK merge appears to be done differently.  The correction can be found in my original merge:
https://github.com/OtherCrashOverride/c2-merge-conflicts/blob/master/lsk-v3.14-15.02/arch/arm64/kernel/setup.c#L482
(note: the change is more than a single line)

The issue is present because there was an upstream kernel patch to the code providing the information.  Git "auto merge" causes the code supplying the information to be removed.  That is why it needed to be manually resolved.

**Comment by meveric** [comment] 2016-05-26 18:51
well seems a lot was changed between these two versions.

so I don't feel comfortible making a diff between these two.

**Comment by OtherCrashOverride** [comment] 2016-05-27 00:41
This is the diff:
https://github.com/OtherCrashOverride/c2-merge-conflicts/commit/4c648c03704aeb3214d6b282c014fcdc4562e434

**Comment by bkrepo** [comment] 2016-05-27 02:45
Thank you for this feedback.
The adding hardware tag commit will upload soon. :-)

**Comment by mdrjr** [comment] 2016-05-27 12:17
5716f8ca79f496d890af709485d5626f856bccdc fixes it.. so i'm closing it.

**Closed as completed by mdrjr** 2016-05-27 12:17 UTC
